// map (dictionary) of potential scanned brand names
// this should be stored within firebase so it can be extended

Map<String, dynamic> polishBrands = {
  "Beetles": "Beetles",
  "BLUCY": "Bluey",
  "china glaze": "China Glaze",
  "DASHING DIMA": "Dashing Diva",
  "DASHING DIVA": "Dashing Diva",
  "ella mila": "ella+mila",
  "ella+mila": "ella+mila",
  "essie": "essie",
  "essié": "essie",
  "L.A. Gill": "L.A. Girl",
  "L.A. Girl": "L.A. Girl",
  "L.A. Girls": "L.A. Girl",
  "L.A. COLORS": "L.A. Colors",
  "MORGAN TAYLOR": "Morgan Taylor",
  "MOROVAN": "Morovan",
  "NAILBERRY": "Nailberry",
  "NAILS INC": "NAILS INC.",
  "NAILS.INC": "NAILS INC.",
  "O.P.I": "O.P.I",
  "ohora": "ohora",
  "OLIVE & JUNE": "Olive & June",
  "OLIVE JUNE": "Olive & June",
  "PIGGY PAINT": "Piggy Paint",
  "REVLON": "Revlon",
  "SALON PERFECT": "Salon Perfect",
  "Sally from": "Sally Hansen",
  "Sally Hans": "Sally Hansen",
  "Sally Hansen": "Sally Hansen",
  "Sally Hanson": "Sally Hansen",
  "Sally Hansong": "Sally Hansen",
  "Sallyffensin": "Sally Hansen",
  "Seche Vive": "seche",
  "Seche Clear": "seche",
  "Seche Vite": "seche",
  "up&up": "up&up",
  "wet n wild": "wet n wild",
  "YEVYO": "YEVYO",
};
